# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'eSteem' do
  pod 'AppCenter/Core'
  pod 'AppCenter/Push', '~> 1.11.0'
  pod 'AppCenter/Crashes'
  pod 'AppCenter/Analytics'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eSteem

  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  

  platform :ios, '9.0'
  target 'eSteemTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'eSteem-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for eSteem-tvOS

  target 'eSteem-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
